CREATE DATABASE MySQLDB-KM;
USE MySQLDB-KM;
CREATE TABLE STUDENT (
	ID VARCHAR(1),
	FullName VARCHAR(1),
);

CREATE TABLE INSTRUCTOR (
	FullName VARCHAR(1),
	ID VARCHAR(1),
);

CREATE TABLE COURSE (
	ID VARCHAR(1),
	Name VARCHAR(1),
	InstructorID VARCHAR(1),
);


